name: Update AoC Badges
on:
  schedule:                                      
    - cron: '6 5 1-25 12 *' 
  push:
    
  workflow_dispatch:                             
jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v2               
      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 969860
          session: ${{ secrets.AOC_SESSION }}
          year: 2023

      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 969860
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2023
          
      - uses: stefanzweifel/git-auto-commit-action@v5     # Step that pushes these local changes back to your github repo
        with:
          commit_message: Update badges
          file_pattern: README.md